[build]
  command = "rm -rf .next && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_USE_YARN = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure Next.js 13+ App Router works
[dev]
  framework = "next"
  targetPort = 3000

[functions]
  node_bundler = "esbuild"
  
# Disable edge functions to avoid deployment issues
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true
  
# Redirect root to dashboard
[[redirects]]
  from = "/"
  to = "/dashboard"
  status = 302
  force = false
  conditions = {Role = ["user"]}



# Environment variables are automatically inherited from Netlify UI
# No need to redefine them here 