[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for better cookie handling
[[headers]]
  for = "/*"
  [headers.values]
    # Allow cookies to be set properly
    Set-Cookie = "SameSite=Lax; Secure"

# Ensure environment variables are properly exposed
[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "${NEXT_PUBLIC_SUPABASE_URL}"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "${NEXT_PUBLIC_SUPABASE_ANON_KEY}" 