[build]
  command = "rm -rf .next node_modules/.cache && npm ci && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  
# Disable edge functions to avoid deployment issues
[build.processing]
  skip_processing = false

[build.processing.images]
  compress = true
  
# Redirect root to dashboard
[[redirects]]
  from = "/"
  to = "/dashboard"
  status = 302
  force = false
  conditions = {Role = ["user"]}



# Environment variables are automatically inherited from Netlify UI
# No need to redefine them here 